### ISSUE TITLE
xcode 6.3 编译错误

### ISSUE THREAD

**Issue by Johnnie-198312** [alibaba/MBMvc#3]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_OMDeferred", referenced from:
      objc-class-ref in libLibMBMVC.a(TBMBPromisesProxy.o)
      objc-class-ref in libLibMBMVC.a(TBMBPromises.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by zephyrleaves** [comment]
try the newset version , there is no TBMBPromisesProxy in 1.2.0
